Collections:
  - Name: KD
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/1503.02531
      Title: Distilling the Knowledge in a Neural Network
    README: configs/distill/mmcls/kd/README.md

Models:
  - Name: kd_logits_resnet34_resnet18_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 2
          Tau: 1
        Metrics:
          Top 1 Accuracy: 71.57
    Config: configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k_w2t1.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_r18_w2/kd_logits_resnet34_resnet18_8xb32_in1k_w2_20221011_164424-ab7f5f6a.pth?versionId=CAEQThiBgIDPgsi0oBgiIDJmNTM5ZmM5YzYwMDRjYTZhOTIxZWIyNjE2YTViOTQ4

  - Name: kd_logits_resnet34_resnet18_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 3
          Tau: 1
        Metrics:
          Top 1 Accuracy: 71.81
    Config: configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k_w3t1.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_r18_w3/kd_logits_resnet34_resnet18_8xb32_in1k_w3_20221011_181115-5c6a834d.pth?versionId=CAEQThiBgID1_Me0oBgiIDE3NTk3MDgxZmU2YjRlMjVhMzg1ZTQwMmRhNmYyNGU2

  - Name: kd_logits_resnet34_resnet18_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 4
          Tau: 1
        Metrics:
          Top 1 Accuracy: 71.73
    Config: configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k_w4t1.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_r18_w4/kd_logits_resnet34_resnet18_8xb32_in1k_w4_20221011_211440-74a2d021.pth?versionId=CAEQThiBgICO9Me0oBgiIDQyZDRhNDQyYmFmNTRkNzE5OTRjMjkzNzg5OWNmNjBh

  - Name: kd_logits_resnet34_resnet18_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 5
          Tau: 1
        Metrics:
          Top 1 Accuracy: 71.75
    Config: configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k_w5t1.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_r18_w5/kd_logits_resnet34_resnet18_8xb32_in1k_w5_20221010_190129-293c39f2.pth?versionId=CAEQThiBgMDd78e0oBgiIDdlMDYwOWFkOTEzZTQ2NWZhYzk1Mjc5YzU1MTUzZTNh

  - Name: kd_logits_resnet34_resnet18_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 5
          Tau: 2
        Metrics:
          Top 1 Accuracy: 71.41
    Config: configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k_w5t2.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_r18_w5t2/kd_logits_resnet34_resnet18_8xb32_in1k_w5t2_20221011_210003-d05e372c.pth?versionId=CAEQThiBgIDa7se0oBgiIDI4MWVhN2Q5NDVjYTRjYWFiY2I3OGVjYjNkM2IxMzdm

  - Name: kd_logits_resnet50_mobilenet-v2_8xb32_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::mobilenet_v2/mobilenet-v2_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth
        Metrics:
          Top 1 Accuracy: 71.86
          Top 5 Accuracy: 90.42
      Teacher:
        Config: mmcls::resnet/resnet50_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth
        Metrics:
          Top 1 Accuracy: 76.55
          Top 5 Accuracy: 93.06
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 5
          Tau: 1
        Metrics:
          Top 1 Accuracy: 73.68
    Config: configs/distill/mmcls/kd/kd_logits_resnet50_mobilenet-v2_8xb32_in1k.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_mbv2/kd_logits_resnet50_mobilenet-v2_8xb32_in1k_20221003_124149-d9548d27.pth?versionId=CAEQThiBgICdqMS0oBgiIGEzMmI1NmIwODI2ODQyODFiM2ZmOTE3NDQ3NmU1Yjhh

  - Name: kd_logits_resnet50_shufflenet-v2-1x_16xb64_in1k
    In Collection: KD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::shufflenet_v2/shufflenet-v2-1x_16xb64_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/shufflenet_v2/shufflenet_v2_batch1024_imagenet_20200812-5bf4721e.pth
        Metrics:
          Top 1 Accuracy: 69.55
          Top 5 Accuracy: 88.92
      Teacher:
        Config: mmcls::resnet/resnet50_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth
        Metrics:
          Top 1 Accuracy: 76.55
          Top 5 Accuracy: 93.06
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Hyper-parameters:
          Loss Weight: 5
          Tau: 1
        Metrics:
          Top 1 Accuracy: 71.27
    Config: configs/distill/mmcls/kd/kd_logits_resnet50_shufflenet-v2-1x_16xb64_in1k.py
    Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmrazor/v1/kd/kl_shuffle/kd_logits_resnet50_shufflenet-v2-1x_16xb64_in1k_20221003_124324-666a2414.pth?versionId=CAEQThiBgMCe78e0oBgiIDdhYjA0NTE4ZDZjMDRmOTU4YzNkN2E2ODNmODUwOGY5
